// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "denkarium.co",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://d19m2sqyq831l1.cloudfront.net",
    "aws_cognito_identity_pool_id": "eu-west-1:18cd263e-8804-4c12-a9c5-2d2cc6ff991a",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_abAAwy9Lu",
    "aws_user_pools_web_client_id": "2fdufct9961nv68hker08ffqmq",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "quotes",
            "region": "eu-west-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "quoteapi",
            "endpoint": "https://l3zptqmqch.execute-api.eu-west-1.amazonaws.com/Prod",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
